### PR TITLE
Add admonition blocks

### PR DESCRIPTION
**Pull request by lucperkins**
This PR adds the ability to easily create so-called admonition blocks, which look like this:

screen shot 2018-10-18 at 10 20 51 am

The "warning" and "info" blocks were introduced in PR #7. This PR makes a few modifications and adds new blocks.

### CODE REVIEW

**Comment by dmcgowan** [comment]
This one needs a rebase now

**Comment by lucperkins** [comment]
@dmcgowan Done

**Comment by mikebrow** [comment]
usually it's because someone uses cut and paste to sign and does not separate the sig line from the subject line..

**Comment by lucperkins** [comment]
What's the appropriate course of action here? I haven't yet run into this.

**Comment by estesp** [comment]
I would `git rebase -i HEAD~2`, change the offending commit to 'edit' from 'pick', then do `git commit --amend` and edit "line 1" to be a short description, leave a blank line, then put additional/longer description (if any needed), then another blank separator line, followed by the `Signed-off-by:` entry (which should already be there in your editor if you are `--amend`ing; finish the commit, and then `git rebase --continue` and `git push -f`

**Comment by mikebrow** [comment]
```
$ git commit --amend 
```
edit the commit make it look like this:

```
short description of commit

Signed-off-by: Name <foo@somemail.com>
```
Save the edit

then force push it up "git push -f origin  branch"

**Comment by estesp** [comment]
Yeah--ignore my rebase stuff; for some reason I thought the offending commit wasn't your "last" one; but you can follow @mikebrow's advice and not do all the rebase stuff. But, if you have a stack of commits, I find the rebase -i capability helpful to go fix up commits not at the "end"

**Comment by mikebrow** [comment]
hmm I pulled down his pr and .. well I don't see anything wrong with his commit signature

**Comment by mikebrow** [comment]
yeah the broke one is the first one.. not sure why travis marked the last one..

**Comment by mikebrow** [comment]
so I think what happened is instead of rebasing.. he created a new commit and in the middle we added the new test for dco.. so boom

**Comment by mikebrow** [comment]
```
mike@mike-VirtualBox:~/go/src/github.com/containerd/containerd.io$ sudo git rebase master
First, rewinding head to replay your work on top of it...
Applying: Add remaning admonition blocks (requirement, danger, success, etc.) plus README documentation
Using index info to reconstruct a base tree...
M	README.md
Falling back to patching base and 3-way merge...
Auto-merging README.md
CONFLICT (content): Merge conflict in README.md
error: Failed to merge in the changes.
Patch failed at 0001 Add remaning admonition blocks (requirement, danger, success, etc.) plus README documentation
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```
so at this stage you open up your fav editor and fix the conflicts.. save the fixed file then

```
mike@mike-VirtualBox:~/go/src/github.com/containerd/containerd.io$ sudo git status
rebase in progress; onto 067f3fa
You are currently rebasing branch 'lperkins/admonitions' on '067f3fa'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   assets/sass/style.sass
	modified:   layouts/partials/admonition.html
	new file:   layouts/shortcodes/danger.html
	modified:   layouts/shortcodes/info.html
	new file:   layouts/shortcodes/requirement.html
	new file:   layouts/shortcodes/success.html
	modified:   layouts/shortcodes/warning.html
	modified:   resources/_gen/assets/sass/sass/style.sass_6af550c30182af2cbd2f775fdbb9d3bc.content
	modified:   resources/_gen/assets/sass/sass/style.sass_6af550c30182af2cbd2f775fdbb9d3bc.json

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

	both modified:   README.md

mike@mike-VirtualBox:~/go/src/github.com/containerd/containerd.io$ sudo git add README.md
mike@mike-VirtualBox:~/go/src/github.com/containerd/containerd.io$ sudo git status
rebase in progress; onto 067f3fa
You are currently rebasing branch 'lperkins/admonitions' on '067f3fa'.
  (all conflicts fixed: run "git rebase --continue")

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   README.md
	modified:   assets/sass/style.sass
	modified:   layouts/partials/admonition.html
	new file:   layouts/shortcodes/danger.html
	modified:   layouts/shortcodes/info.html
	new file:   layouts/shortcodes/requirement.html
	new file:   layouts/shortcodes/success.html
	modified:   layouts/shortcodes/warning.html
	modified:   resources/_gen/assets/sass/sass/style.sass_6af550c30182af2cbd2f775fdbb9d3bc.content
	modified:   resources/_gen/assets/sass/sass/style.sass_6af550c30182af2cbd2f775fdbb9d3bc.json

mike@mike-VirtualBox:~/go/src/github.com/containerd/containerd.io$ sudo git rebase --continue
Applying: Add remaning admonition blocks (requirement, danger, success, etc.) plus README documentation
mike@mike-VirtualBox:~/go/src/github.com/containerd/containerd.io$ sudo git status
On branch lperkins/admonitions
nothing to commit, working directory clean
```
then from there fix the commit header that's too long via:
```
mike@mike-VirtualBox:~/go/src/github.com/containerd/containerd.io$ sudo git commit --amend
[lperkins/admonitions 90d060b] Add remaning admonition blocks (requirement, danger, success, etc.) plus README
 Author: lucperkins <lucperkins@gmail.com>
 Date: Thu Oct 18 10:24:21 2018 -0700
 10 files changed, 44 insertions(+), 11 deletions(-)
 create mode 100644 layouts/shortcodes/danger.html
 create mode 100644 layouts/shortcodes/requirement.html
 create mode 100644 layouts/shortcodes/success.html
```
node just need to delete the last word there.. then 
$ git push -f origin branch

hope this helps cheers

**Comment by lucperkins** [comment]
@mikebrow Thanks a lot for your help! This should be all squared away now.

**Pull request merged**
