### PR TITLE
Add adopter logos

### PR DESCRIPTION
**Pull request by lucperkins**
@estesp This isn't all of them, as some of the projects don't appear to have official logos just yet, but I think that this is a good start. You can see the new section here:

https://deploy-preview-27--containerd-io.netlify.com/#adopters

### CODE REVIEW

**Comment by estesp** [comment]
Looking good; based on comments on the containerd graduation proposal in the CNCF, we should add [Kata containers](https://katacontainers.io/) logo, and now AWS announced ["Firecracker"](https://github.com/firecracker-microvm/firecracker) early this week, which uses containerd as well--so we might as well add their logo too.

**Comment by lucperkins** [comment]
@estesp Done. There were a few projects that didn't have logos AFAICT. I'll be on the lookout for those, but this should be good to go for now.

**Comment by crosbymichael** [comment]
You'll need to squash your commits

**Comment by lucperkins** [comment]
@crosbymichael Done

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
