### PR TITLE
adopters: remove eliot.run

### PR DESCRIPTION
**Pull request by samuelkarp**
Eliot appears to be defunct and the domain is for sale.

### CODE REVIEW

**Review by akhilerm — APPROVED** [review]
/lgtm

**Review by estesp — APPROVED** [review]

**Comment by akhilerm** [comment]
@samuelkarp There is a reference of Eliot in https://github.com/containerd/containerd/blame/main/ADOPTERS.md#L35, Should that also be removed?. Its not a broken link since it points to the github repo of the project.

**Comment by samuelkarp** [comment]
@akhilerm Last update of that repo looks to be 5 years ago (2018), so yeah I'd probably remove it.

**Comment by akhilerm** [comment]
Will raise a PR to remove it.

**Pull request merged**
