### PR TITLE
Update to latest version 1.6.15

### PR DESCRIPTION
**Pull request by estesp**
Also try and force the downloads page to re-render in Hugo.

Signed-off-by: Phil Estes <estesp@amazon.com>

### CODE REVIEW

**Comment by dcantah** [comment]
Hmm, got a 403 it seems: 7:15:44 AM: Building sites … ERROR 2023/01/17 15:15:44 Failed to get JSON resource "https://api.github.com/repos/containerd/containerd/releases?per_page=50&page=1": Failed to retrieve remote file: Forbidden

**Comment by estesp** [comment]
Tempfail on netlify deploy due to GitHub API rate limit; re-ran and worked (but doesn't update the PR): https://63c6c3c31de77f55acfce153--containerd-io.netlify.app/

**Comment by estesp** [comment]
@dcantah yeah, see above ^^ (seems Netlify might have temporarily hit a rate limit on the GH API; was working locally at that time, and now working again on Netlify)

**Review by dcantah — APPROVED** [review]

**Comment by AkihiroSuda** [comment]
Not sure how to restart the netlify CI, but I guess we can safely merge this

**Comment by estesp** [comment]
Yeah, sorry--I had already run it manually through the netlify dashboard. Thanks

**Pull request merged**
