### PR TITLE
Add link checker

### PR DESCRIPTION
**Pull request by lucperkins**
This PR adds a link checker to the site build and fixes existing broken links.

cc @estesp

### CODE REVIEW

**Comment by estesp** [comment]
My only issue with this change (and reveals a problem in our design here) is that releases.md is a copy from `containerd/containerd` repo, and I now have a GitHub Action that keeps them in sync, since they were always getting out of sync. So, making changes to it will be overwritten the next time the GH action creates a PR with changes from the "master" copy. If you want I can programmatically make the action do those fixups.. since the design flaw is thinking we could copy a markdown file out of another repo, which clearly has links that work in that repo, but not in this one..

**Comment by lucperkins** [comment]
@estesp Ah, okay, that is definitely an issue. Proposed course of action: I make the checker optional and something that can be run locally but isn't enforced at the CI level. If you find a different way of handling the `release.md` workflow we can revisit enforcing it in CI. Does that sound about right?

**Comment by estesp** [comment]
I've just added modifiers to the copied-in releases.md to the GitHub Action; will open PR in a minute. It should do the same thing you had done manually in the PR every time it copies in changes. We can verify it on the first run.

**Comment by lucperkins** [comment]
@estesp Okay, sounds good. Just let me know if at some point you want to "activate" the check in CI.

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
