### PR TITLE
New website

### PR DESCRIPTION
**Pull request by lucperkins**
This PR fundamentally reworks the containerd website. You can see a preview of that work here:

https://containerd-website-sandbox.netlify.com

### CODE REVIEW

**Comment by estesp** [comment]
I like how the new site is coming together; I have no comments on the file changes in the PR as it looks reasonable--so I assume this matches the source content for the new site :)

LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by stevvooe** [comment]
Doesn't this have commit history? That should be perserved before importing everything. "Move website assets from main containerd repo" makes me think there was existing history there.

**Comment by crosbymichael** [comment]
Most of the files were already moved by @estesp , i don't think anything in the commit history here is valuable or intended by the commit message

**Comment by lucperkins** [comment]
@stevvooe There *is* a commit history here, but I basically built the site in a different repo and thus don't have a way to transmit that history here. I'd be happy to update the commit message, though, which was basically an afterthought anyway.

@estesp Yep! This is indeed the source for the site you see via the Netlify link :)

**Comment by dmcgowan** [comment]
LGTM

For the commit history, we currently don't plan on removing the files from the original repository. This may be a copy and not a move, but let's merge this

**Pull request merged**
