### PR TITLE
Add click popup for clipboard links on downloads page

### PR DESCRIPTION
**Pull request by lucperkins**
If you click on links in the **Copy link** column on the [downloads page](https://deploy-preview-20--containerd-io.netlify.com/downloads/), you'll get a little popup indicating that the link has been coped to the clipboard.

### CODE REVIEW

**Comment by mikebrow** [comment]
I can remember when it used to only take a couple lines of code to put up a message. 4k of js seems a bit heavy.. just sayin.

**Comment by lucperkins** [comment]
@mikebrow True, but I unfortunately don't have the bandwidth for that. You're welcome to take a crack at it, though 😄

**Comment by mikebrow** [comment]
> @mikebrow True, but I unfortunately don't have the bandwidth for that. You're welcome to take a crack at it, though 😄

fair enough :-) let's merge this and I'll put it on my stack of to dos

**Comment by lucperkins** [comment]
@mikebrow Sounds good to me!

**Comment by estesp** [comment]
@mikebrow:
| fair enough :-) let's merge this and I'll put it on my stack of to dos

no, just no. 👴 you and I and our hand-crafted HTML/CSS/JS was great in the 90s; we have better things to do than worry about modern Javascript framework sizes 😄

**Pull request merged**
