### PR TITLE
Update latest release to 1.6.12

### PR DESCRIPTION
**Pull request by mzaian**
Signed-off-by: Mohamed Zaian <mohamedzaian@gmail.com>

### CODE REVIEW

**Review by estesp — APPROVED** [review]
LGTM

Not sure why your PR ended up with an extra (empty) "merge commit"; maybe you can squash and re-push so it's just the "update to latest release"?

**Comment by mzaian** [comment]
> LGTM
> 
> Not sure why your PR ended up with an extra (empty) "merge commit"; maybe you can squash and re-push so it's just the "update to latest release"?

I messed up because I did not rebase before committing this.

**Comment by estesp** [comment]
Can you update your PR to 1.6.12? We had a quick follow-up release for the CVE in CRI Exec, so now the latest is already 1.6.12. Thanks!

**Comment by mzaian** [comment]
> Can you update your PR to 1.6.12? We had a quick follow-up release for the CVE in CRI Exec, so now the latest is already 1.6.12. Thanks!

Done :)

**Review by estesp — APPROVED** [review]
LGTM

**Pull request merged**
