### PR TITLE
containerd downloads page

### PR DESCRIPTION
**Pull request by lucperkins**
This PR establishes a downloads page for containerd and updates the getting started guide to direct users to the downloads page (rather than to the GitHub Releases page). I'm not super familiar with installing and running containerd so feel free to provide critiques on content, formatting, etc.

You can see a preview of that page [here](https://deploy-preview-11--containerd-io.netlify.com/downloads).

### CODE REVIEW

**Comment by estesp** [comment]
Needs a rebase after the admonition blocks merge @lucperkins ; thanks!

**Comment by lucperkins** [comment]
@estesp Done

**Comment by lucperkins** [comment]
@estesp Heads up: I modified this PR to use a table for the release downloads, which I think provides a much more compact look. If you could review the latest version, that'd be great.

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
